name: Deploy Python App to Azure Web App

on:
  push:
    branches:
      - main
      
  workflow_dispatch:  # Manual trigger


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install python dependencies
        working-directory: ./app
        run: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip application
        run: zip -r app.zip ./app

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SP_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: simple-azure-web-app-app-01
          package: ./app.zip
          startup-command: python app.py

